### ISSUE TITLE
util: Service/Layer map

### ISSUE THREAD

**Issue by LucioFranco** [tower-rs/tower#243] opened 2019-04-09 18:59 UTC
A service to map the request type within a stack of services. This should provide the ability maybe just for now to sync or async change the request type of a service stack.

**Comment by davidbarsky** [comment] 2019-04-09 19:41
Does this entail supporting multiple request types per service/stack, instead of the one-per-service model we have at the moment?

**Comment by carllerche** [comment] 2019-04-09 20:16
There were map and map_err combinators. That was pre- `ServiceBuilder`. We should figure out the best way to re-introduce this.

**Comment by jonhoo** [comment] 2020-03-31 21:58
I assume this is a duplicate of #272?

**Comment by LucioFranco** [comment] 2020-03-31 22:20
👍 I have an implementation of this for vector I can bring it over if you want to assign me the correct issue.

**Comment by jonhoo** [comment] 2020-03-31 22:21
Closing as a dupe, and making #272 the main issue.

**Closed by jonhoo** 2020-03-31 22:21 UTC
Labels: A-new-middleware, C-feature-request, S-duplicate
